<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use App\Events\CallLogged;
use Illuminate\Support\Facades\Event;

class CallFlowTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();
        // Since sqlite clears, run seeder
        $this->artisan('db:seed');
    }

    public function test_crm_agent_can_view_dashboard()
    {
        // Fetch super admin generated by seeder
        $user = User::first();
        
        $response = $this->actingAs($user)->get('/dashboard');
        $response->assertStatus(200);
        $response->assertSee('Operational Dashboard');
    }

    public function test_crm_agent_can_create_call_and_trigger_event()
    {
        Event::fake();

        $user = User::first();
        $callType = DB::table('call_types')->first();
        
        $response = $this->actingAs($user)->post('/calls', [
            'caller_number' => '0300-1234567',
            'call_type_id' => $callType->id,
            'caller_name' => 'John Doe',
            'details' => 'Vehicle broken down on M2',
        ]);

        $response->assertRedirect('/dashboard');
        $response->assertSessionHas('success');

        // Assert database values
        $this->assertDatabaseHas('calls', [
            'caller_number' => '0300-1234567',
            'status' => 'pending'
        ]);

        // Assert ACID transactions generated the subsequent audit and workflow tables correctly
        $call = DB::table('calls')->first();
        $this->assertDatabaseHas('call_status_history', ['call_id' => $call->id]);
        $this->assertDatabaseHas('audit_logs', ['record_id' => $call->id]);

        // Assert broadcasting system deployed events securely 
        Event::assertDispatched(CallLogged::class, function ($event) use ($call) {
            return $event->callNumber === $call->call_number;
        });
    }
}
